// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package kotlin

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComTabbedSqlcGenKotlinInternal(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "package":
			out.Package = string(in.String())
		case "emit_exact_table_names":
			out.EmitExactTableNames = bool(in.Bool())
		case "inflection_exclude_table_names":
			if in.IsNull() {
				in.Skip()
				out.InflectionExcludeTableNames = nil
			} else {
				in.Delim('[')
				if out.InflectionExcludeTableNames == nil {
					if !in.IsDelim(']') {
						out.InflectionExcludeTableNames = make([]string, 0, 4)
					} else {
						out.InflectionExcludeTableNames = []string{}
					}
				} else {
					out.InflectionExcludeTableNames = (out.InflectionExcludeTableNames)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.InflectionExcludeTableNames = append(out.InflectionExcludeTableNames, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComTabbedSqlcGenKotlinInternal(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"package\":"
		out.RawString(prefix[1:])
		out.String(string(in.Package))
	}
	{
		const prefix string = ",\"emit_exact_table_names\":"
		out.RawString(prefix)
		out.Bool(bool(in.EmitExactTableNames))
	}
	{
		const prefix string = ",\"inflection_exclude_table_names\":"
		out.RawString(prefix)
		if in.InflectionExcludeTableNames == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.InflectionExcludeTableNames {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComTabbedSqlcGenKotlinInternal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComTabbedSqlcGenKotlinInternal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComTabbedSqlcGenKotlinInternal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComTabbedSqlcGenKotlinInternal(l, v)
}
