name: go
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@883c70a44e3c9e260598ae09034c92b51f2c9129
    # - uses: sqlc-dev/setup-sqlc@v4
    #   with:
    #     sqlc-version: '1.24.0'
    - run: make
    - run: sqlc diff
      working-directory: examples