name: go
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    # - run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@main
    - uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.25.0'
    - run: make
    - run: sqlc diff
      working-directory: examples
